name: Build & Test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Show Xcode Version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild -scheme AccessAssociatedValueClient -destination "platform=macOS"
      - name: Test
        run: xcodebuild test -scheme AccessAssociatedValueTests -destination "platform=macOS"
