name: Build & Test
on: [push]
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
        with:
          xcode-version: '15.0.1'
      - name: Show Xcode Version
        run: xcodebuild -version
      - name: Build AccessAssociatedValueClient
        run: xcodebuild -scheme AccessAssociatedValueClient -destination "platform=macOS"
      - name: Test AccessAssociatedValueTests
        run: xcodebuild test -scheme AccessAssociatedValueTests -destination "platform=macOS"
