name: Test
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - name: Show Xcode Version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild test -scheme AccessAssociatedValueTests -destination "platform=macOS"
